# Generated by Django 4.2.2 on 2023-06-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Type_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset_Type', models.TextField(max_length=20)),
                ('Asset_Description', models.TextField(max_length=500)),
                ('Created_At', models.DateTimeField(default='Thu Jun 22 12:10:36 2023')),
                ('Updated_At', models.DateTimeField(default='Thu Jun 22 12:10:36 2023')),
            ],
        ),
    ]
