# Generated by Django 4.2.2 on 2023-06-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_Tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_type_model',
            name='Created_At',
            field=models.DateTimeField(default='Thu Jun 22 12:13:28 2023'),
        ),
        migrations.AlterField(
            model_name='asset_type_model',
            name='Updated_At',
            field=models.DateTimeField(default='Thu Jun 22 12:13:28 2023'),
        ),
    ]
