# Generated by Django 4.2.2 on 2023-06-23 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_Tracker_app', '0003_assettypemodel_delete_asset_type_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetName', models.TextField()),
                ('AssetType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asset_Tracker_app.assettypemodel')),
            ],
        ),
    ]
