# Generated by Django 4.2.2 on 2023-06-23 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_Tracker_app', '0006_alter_assettypemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='AssetCode',
            field=models.TextField(default='3871a358-1190-11ee'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 6, 36, 1, 500430)),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='Updated_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 6, 36, 1, 500443)),
        ),
        migrations.AlterField(
            model_name='assettypemodel',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 6, 36, 1, 499988)),
        ),
        migrations.AlterField(
            model_name='assettypemodel',
            name='Updated_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 6, 36, 1, 500004)),
        ),
    ]
