# Generated by Django 4.2.2 on 2023-06-23 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_Tracker_app', '0007_assetmodel_assetcode_assetmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='AssetCode',
            field=models.TextField(default='87f2dd0d-1190-11ee'),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 6, 38, 14, 887285)),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Updated_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 6, 38, 14, 887297)),
        ),
        migrations.AlterField(
            model_name='assettypemodel',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 6, 38, 14, 886823)),
        ),
        migrations.AlterField(
            model_name='assettypemodel',
            name='Updated_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 6, 38, 14, 886839)),
        ),
    ]
