# Generated by Django 4.2.2 on 2023-06-23 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_Tracker_app', '0010_alter_assetmodel_assetcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='AssetCode',
            field=models.TextField(default='5a25f1b1-206f-4343'),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 7, 52, 9, 449306)),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Updated_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 7, 52, 9, 449319)),
        ),
        migrations.AlterField(
            model_name='assettypemodel',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 7, 52, 9, 448846)),
        ),
        migrations.AlterField(
            model_name='assettypemodel',
            name='Updated_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 7, 52, 9, 448861)),
        ),
    ]
