# Generated by Django 4.2.2 on 2023-06-23 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_Tracker_app', '0011_alter_assetmodel_assetcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='AssetCode',
            field=models.IntegerField(default='36fac76b-449e-4d75'),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 8, 8, 15, 469913)),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Updated_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 8, 8, 15, 469927)),
        ),
        migrations.AlterField(
            model_name='assettypemodel',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 8, 8, 15, 469300)),
        ),
        migrations.AlterField(
            model_name='assettypemodel',
            name='Updated_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 8, 8, 15, 469318)),
        ),
    ]
