# Generated by Django 4.2.2 on 2023-06-24 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Asset_Tracker_app",
            "0023_assetmodel_status_alter_assetmodel_assetcode_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="assetmodel",
            old_name="status",
            new_name="Active_Status",
        ),
        migrations.AlterField(
            model_name="assetmodel",
            name="AssetCode",
            field=models.TextField(default="28c5d1d3-e410-4932"),
        ),
        migrations.AlterField(
            model_name="assetmodel",
            name="Created_At",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 24, 10, 38, 50, 604470)
            ),
        ),
        migrations.AlterField(
            model_name="assetmodel",
            name="Updated_At",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 24, 10, 38, 50, 604485)
            ),
        ),
        migrations.AlterField(
            model_name="assettypemodel",
            name="Created_At",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 24, 10, 38, 50, 603962, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="assettypemodel",
            name="Updated_At",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 24, 10, 38, 50, 603989, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
